CREATE TABLE USER ( ID INT PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), DATEBIRTH DATE, STATUS BOOLEAN );
CREATE TABLE country (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO country (name) VALUES ('India');
INSERT INTO country (name) VALUES ('Brazil');
INSERT INTO country (name) VALUES ('USA');
INSERT INTO country (name) VALUES ('Italy');